name: Sync Organization Labels

on:
  workflow_dispatch:   # allows manual trigger
  schedule:
    - cron: "0 2 * * *"  # optional: runs daily at 2 AM UTC

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Apply organization-default labels
        run: |
          ORG_NAME="the-homburg-foundation"
          LABELS=(
            "base|1f77b4|Tasks related to the core system and derpy-base repository"
            "iso|ff7f0e|Tasks related to ISO creation, bootloader, or installer"
            "desktop|2ca02c|Tasks related to desktop environment and GUI applications"
            "repo|d62728|Tasks related to package repository setup and package management"
            "docs|9467bd|Tasks for documentation, guides, and release notes"
            "website|8c564b|Tasks for website content, ISO downloads, and linking resources"
            "security|e377c2|Tasks related to security hardening or package verification"
            "testing|7f7f7f|Tasks involving testing, QA, or VM verification"
          )

          for repo in $(gh repo list $ORG_NAME --json name -q '.[].name'); do
            echo "Updating labels for $repo"
            for label in "${LABELS[@]}"; do
              IFS='|' read -r name color desc <<< "$label"
              gh label create "$name" --color "$color" --description "$desc" --repo "$ORG_NAME/$repo" || echo "Label $name exists in $repo"
            done
          done
